//for Category
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const GET_ERROR = "GET_ERROR";
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY"
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY"
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY"

//for Brands
export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const CREATE_BRAND = "CREATE_BRAND"
export const GET_ONE_BRAND = "GET_ONE_BRAND"

//FOR PRODUCT 
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT"
export const GET_ALL_PRODUCT_WITH_SORT = "GET_ALL_PRODUCT_WITH_SORT"
export const GET_SPECIFIC_PRODUCT = "GET_SPECIFIC_PRODUCT"
export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE"
export const DELETE_PRODUCT = "DELETE_PRODUCT"